### ISSUE TITLE
Feature request: ability to choose a specific size for `src` attribute

### ISSUE THREAD

**Issue by d9beuD** [lawmurray/jekyll-responsive-magick#1]
Hi @lawmurray! I use your plugin for a couple days now and it works like **magic**. Thanks for you work!

On my websites, I have images which won't be wider than 480px. I think it would be nice to have a filter that can trigger ImageMagick to shrink an image to a specific value.

```liquid
<img src="{ post.image | size: '480px' }" alt="...">
```

It would output something like this:

```html
<img src="/assets/images/test-480w.jpg" alt="...">
```

What do you think about this? Do you think you could implement such a filter? I'm not a Ruby developper, but let me know if you want help implementing this.

**Comment by lawmurray** [comment]
Thanks for the suggestion @d9beuD, would be happy to accept a contribution on this.

As an alternative, if you add a width of 480 to your [configuration](https://github.com/lawmurray/jekyll-responsive-magick#configuration), then you could use the usual `srcset` and specify a fixed `width="480"` in your `img` tag. Browsers should then pick out the 480-width version to display.

**Comment by d9beuD** [comment]
Alright I'll try my best to create the suggested filter.

I understand your alternative, but if one wants to use a background image, it can't be used:

```liquid
{# this won't work #}
<div style="background-image: url({ post.image | srcset });"></div>
```
