### ISSUE TITLE
`size` filter does not support webp image format

### ISSUE THREAD

**Issue by d9beuD** [lawmurray/jekyll-responsive-magick#4]
Say I use the filter like `{{ "/assets/img/test.png" | size: 480 }}` then it outputs `/assets/img/test-480w.png`. But if the file is `test.webp` it outputs `/assets/img/` without the file name. 

I think it's because of the following line, but the `srcset` function has it too, yet it works.

https://github.com/lawmurray/jekyll-responsive-magick/blob/4f809ea4a0629f7ea728bb26629498446397479b/lib/jekyll-responsive-magick.rb#L145

**Comment by lawmurray** [comment]
Thanks @d9beuD. Happy to accept a pull request to fix this if you have the time. Probably just a case of adding .webp to the list of acceptable file extensions, as ImageMagick already supports the format I believe.

**Comment by d9beuD** [comment]
What do you think about checking the mime type of the file instead of the extension? I don't know Ruby enough to say if it's doable, but:

```ruby
if File.exist?(src) and File.mime?(src, "image/*)
```

instead of the line I quoted in my original comment. If you're okay with this idea, assign me to the issue and I'll try my best to make it work.

**Comment by lawmurray** [comment]
Nice idea if you can get it working @d9beuD. That should open up support for any image formats that ImageMagick supports. Assigned you the ticket, thanks for the contributions!
