### ISSUE TITLE
Broken Images When Displaying For The Responsive Mode

### ISSUE THREAD

**Issue by leonism** [lawmurray/jekyll-responsive-magick#8]
I think, I've managed to run the Responsive Images with Jekyll and ImageMagick, by using the following usage :

```
  <img
              itemprop="image"
              src="{{ post.background }}"
              srcset="{{ post.background | srcset }}"
              width="{{ post.background | width }}"
              height="{{ post.background | height }}"
              class="card-img-top img-fluid"
              alt="{{ post.title }}">
```
It produced the output images under the __responsive_ folder. But the html output is not something I would expect, since the path is slightly different 

```
<img itemprop="image" src="/assets/img/bg-about.webp" 
srcset="/assets/img/bg-about.webp 2336w, 
/assets/img/bg-about-400w.webp 400w, 
/assets/img/bg-about-500w.webp 500w, 
/assets/img/bg-about-700w.webp 700w, 
/assets/img/bg-about-900w.webp 900w" 
width="2336" height="1558" 
class="card-img-top img-fluid" 
alt="Some alternate text goes here">
```

Now it's calling for the default path, but the output path is located under the __responsive_ folder, and for some reasons, the __responsive_ folder is not getting copy to the __site_ folder? Any ideas, what had I misconfigured wrong?

Thanks,

**Comment by lawmurray** [comment]
Hi @leonism. The `_responsive` directory is the cache, but its contents should be copied over into your `_site` directory when you build, so that the resized images appear alongside the original. In your example, looks like the original image should end up at `_site/assets/img/bg-about.webp`, and the resized images should be alongside it, such as `_site/assets/img/bg-about-400w.webp`.

That's not what you're seeing?

**Comment by leonism** [comment]
And after hours trying to figuring out what went wrong, turned out that I had couple of Jekyll's permission & caching issues, once invoking the following command, it settled the problems, I'm gonna put the solutions here for anyone coming for the same issues :

1. Change the ownership of the Jekyll directory: You can change the ownership of the Jekyll directory to the current user with the `chown` command. Replace username with your username:

`sudo chown -R username /path/to/my-projects/`

2. Change the permissions of the Jekyll directory: You can change the permissions of the Jekyll directory to allow the current user to read, write, and execute files in the directory with the `chmod` command:

`sudo chmod -R 755 /path/to/my-projects/`

3. Delete the cache: If the problem persists, try deleting the `.jekyll-cache` directory and then run the Jekyll command again:

`rm -rf /path/to/my-projects/.jekyll-cache`

Please be careful when using `sudo`, `chown`, `chmod`, and `rm -rf`, as they are powerful commands that can modify or delete important files if used incorrectly. After fixed the problems, Jekyll started to copy the content at `_responsive` folder to the `_site` folder.
 

Thanks @lawmurray
